### ISSUE TITLE
2nd edition?

### ISSUE THREAD

**Issue by slimshader** [la-yumba/functional-csharp-code-2#1]
Does this repo mean that 2nd edition of your amazing book is coming...? ;)

**Comment by la-yumba** [comment]
@slimshader Yes! I just started work on the 2nd edition, which will be updated to reflect new C# 8 and 9 features. Thanks for your kind words!

**Comment by slimshader** [comment]
Fantastic news. I've read 1st edition 3 times to finally get the most of it and my code is not the same since.
