### ISSUE TITLE
Enable Github Discussions for this repository?

### ISSUE THREAD

**Issue by JonTheTurnip** [la-yumba/functional-csharp-code-2#11]
Hi there,

It would great to enable [Github discussions](https://docs.github.com/en/discussions/quickstart) on this repository as I'm sure there are plenty of developers who have read the excellent book by Enrico and have further questions, I'm sure a small community could develop here.

Cheers

Jon

**Comment by la-yumba** [comment]
Thanks for the suggestion, I've now enabled discussions. There is a space for discussions in the online book, but I agree that for issues that relate specifically to the code, and not so much to the ideas, having the discussion here on Github makes sense.
