### ISSUE TITLE
Contact regarding EventStoreDB

### ISSUE THREAD

**Issue by dairyleia** [la-yumba/functional-csharp-code-2#14]
Hi there, My name is Steph Gill, I'm Community Engager from Event Store. Several of the team at Event Store have read your book and really enjoyed it, especially Alexey Zimarev and Yves Lorphelin. I'd love to talk to you a bit more about it! Can you please email me at steph.gill@eventstore.com so we can talk further? 

Thanks and have a good day!

Steph Gill

**Comment by la-yumba** [comment]
Hi, thanks for getting in touch, I've emailed you.
