### ISSUE TITLE
NuGet.config breaks `dotnet build`

### ISSUE THREAD

**Issue by ReneB** [la-yumba/functional-csharp-code-2#2]
Hi, TDE for the book here - pleased to meet you!

The certificate for `dotnet.myget.org` has expired and from what I read online, they're not planning to renew it at all. This line therefore causes issues with `dotnet build` - but at least in my environment, when I removed it entirely it "just worked" ("it" being `dotnet restore && dotnet build`), probably because `dotnet-core` can already be found in official NuGet repos?

https://github.com/la-yumba/functional-csharp-code-2/blob/b61d0a7fa09e841d1d62fe978064006497d2bfb1/NuGet.Config#L4

**Comment by la-yumba** [comment]
Hi René, thanks so much for looking into this. This is now fixed :-)
