### ISSUE TITLE
NuGet.Config does not contain a source for FeatherHttp

### ISSUE THREAD

**Issue by ReneB** [la-yumba/functional-csharp-code-2#3]
When attempting `dotnet restore` or `dotnet build`, the system responds with

`error NU1101: Unable to find package FeatherHttp. No packages exist with this id in source(s): fsCheck-appVeyor, nuget.org`

Adding a source for FeatherHttp would solve this.

**Comment by la-yumba** [comment]
Yes - so now I've done that, and it works with the dotnet CLI. I did get some errors restoring featherHttp on VisualStudio Community for Mac, that's why initially I had included a local package source...

**Comment by ReneB** [comment]
Yeah, I used to be a Visual Studio Community for Mac user as well but it's the pits. At some point I completely ditched it in favor of Visual Studio Code which was much more configurable and allowed me to actually solve issues when I found them by using the right plugins. I think Visual Studio for Mac is just a rebranded Xamarin Studio and I often wonder about its reason for existing when - in my experience at least - VS Code is the better product _and_ works cross-platform...
